#!/bin/sh
changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|vue|svelte)$')

if [ -n "$changed_files" ]; then
  echo "🔍 Анализ изменённых файлов:"
  echo "$changed_files" | xargs eslint --fix
fi